### ISSUE TITLE
Breaking leading slash during upload in a directory

### ISSUE THREAD

**Issue by sylvainDNS** [trieb-work/strapi-provider-cloudflare-r2#13] opened 2023-11-20 21:44 UTC
Hi & thank you for this lib!

I'm having a problem uploading a file into a directory created on strapi.
Here's the url produced: `https://pub-random-bucket-id.r2.dev//1/1_d64fc29c7e.png`

You may notice an extra / character. In my Cloudflare bucket, an extra directory has been created.
Actual path: `/` > `1` > `1_d64fc29c7e.png`
Expected path: `1` > `1_d64fc29c7e.png`

This directory (`/`) will then break the url validator of my front-end framework. I made a patch on my local environment, but I can make a PR.

Thanks!

**Comment by JannikZed** [comment] 2023-11-21 09:30
Hi @sylvainDNS thank you for the PR, that sounds all good! My question is: how exactly can I reproduce this behavior. I'm using folders in Strapi as well and the upload always works.

**Comment by sylvainDNS** [comment] 2023-11-21 10:34
The upload works, but produces an "invalid" URL caused by the `/` directory. It is when I consume the url that the error comes. So maybe the tool you use to consume the url is less strict than mine (Astro framework with Image/Picture component).

From what I see on the web, a double slash is not forbidden, but not recommended. 🤷 

But please note that this change can be seen as a breaking change, since the new files uploaded in a directory on strapi won't be in the same directory on the bucket as the old ones.

**Comment by JannikZed** [comment] 2023-11-21 10:55
got it! Can reproduce - strangely, it still works for me, even with the double slash, but yes, that should be fixed.

**Closed as completed** 2023-11-21 10:55 UTC
Labels: released
